# Generated by Django 3.2 on 2021-05-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SciencePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=255)),
                ('submitter', models.CharField(max_length=255)),
                ('funding', models.FloatField()),
                ('objectives', models.TextField(max_length=255)),
                ('star_system', models.CharField(choices=[('Andromeda', 'Andromeda'), ('Air Pump', 'Air Pump'), ('Bird of Paradise', 'Bird of Paradise'), ('Water Bearer', 'Water Bearer'), ('Eagle', 'Eagle'), ('Altar', 'Altar'), ('Ram', 'Ram'), ('Charioteer', 'Charioteer'), ('Herdsman', 'Herdsman'), ('Chisel', 'Chisel'), ('Giraffe', 'Giraffe'), ('Crab', 'Crab'), ('Hunting Dogs', 'Hunting Dogs'), ('Greater Dog', 'Greater Dog'), ('Lesser Dog', 'Lesser Dog'), ('Sea Goat', 'Sea Goat'), ('Keel', 'Keel'), ('Cassiopeia', 'Cassiopeia'), ('Centaur', 'Centaur'), ('Cepheus', 'Cepheus'), ('Whale (or Sea Monster)', 'Whale (or Sea Monster)'), ('Chameleon', 'Chameleon'), ('Compass (drafting tool)', 'Compass (drafting tool)'), ('Dove', 'Dove'), ('Berenice’s Hair', 'Berenice’s Hair'), ('Southern Crown', 'Southern Crown'), ('Northern Crown', 'Northern Crown'), ('Crow', 'Crow'), ('Cup', 'Cup'), ('Southern Cross', 'Southern Cross'), ('Swan', 'Swan'), ('Dolphin', 'Dolphin'), ('Dolphinfish', 'Dolphinfish'), ('Dragon', 'Dragon'), ('Little Horse (Foal)', 'Little Horse (Foal)'), ('Eridanus (river)', 'Eridanus (river)'), ('Furnace', 'Furnace'), ('Twins', 'Twins'), ('Crane', 'Crane'), ('Hercules', 'Hercules'), ('Pendulum Clock', 'Pendulum Clock'), ('Hydra', 'Hydra'), ('Water Snake', 'Water Snake'), ('Indian', 'Indian'), ('Lizard', 'Lizard'), ('Lion', 'Lion'), ('Lesser Lion', 'Lesser Lion'), ('Hare', 'Hare'), ('Scales', 'Scales'), ('Wolf', 'Wolf'), ('Lynx', 'Lynx'), ('Lyre', 'Lyre'), ('Table Mountain (Mons Mensae)', 'Table Mountain (Mons Mensae)'), ('Microscope', 'Microscope'), ('Unicorn', 'Unicorn'), ('Fly', 'Fly'), ('Level', 'Level'), ('Octant', 'Octant'), ('Serpent Bearer', 'Serpent Bearer'), ('Orion (the Hunter)', 'Orion (the Hunter)'), ('Peacock', 'Peacock'), ('Pegasus', 'Pegasus'), ('Perseus', 'Perseus'), ('Phoenix', 'Phoenix'), ('Easel', 'Easel'), ('Fishes', 'Fishes'), ('Southern Fish', 'Southern Fish'), ('Stern', 'Stern'), ('Compass (mariner’s compass)', 'Compass (mariner’s compass)'), ('Reticle', 'Reticle'), ('Arrow', 'Arrow'), ('Archer', 'Archer'), ('Scorpion', 'Scorpion'), ('Sculptor', 'Sculptor'), ('Shield (of Sobieski)', 'Shield (of Sobieski)'), ('Snake', 'Snake'), ('Sextant', 'Sextant'), ('Bull', 'Bull'), ('Telescope', 'Telescope'), ('Triangle', 'Triangle'), ('Southern Triangle', 'Southern Triangle'), ('Toucan', 'Toucan'), ('Great Bear', 'Great Bear'), ('Little Bear', 'Little Bear'), ('Sails', 'Sails'), ('Virgin (Maiden)', 'Virgin (Maiden)'), ('Flying Fish', 'Flying Fish'), ('Fox', 'Fox')], max_length=255)),
                ('telescope_location', models.CharField(choices=[('HAWAII', 'HAWAII'), ('CHILE', 'CHILE')], max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
