# Generated by Django 3.2 on 2021-05-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_app', '0003_auto_20210509_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scienceplan',
            old_name='hightlights',
            new_name='highlights',
        ),
    ]
