# Generated by Django 3.2 on 2021-05-09 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_app', '0004_rename_hightlights_scienceplan_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scienceplan',
            name='creator',
            field=models.CharField(default="Creator's name", max_length=50),
        ),
        migrations.AlterField(
            model_name='scienceplan',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 14, 19, 12, 136267, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scienceplan',
            name='objectives',
            field=models.TextField(default='Objectives of this science plan', max_length=255),
        ),
        migrations.AlterField(
            model_name='scienceplan',
            name='star_system',
            field=models.CharField(choices=[('Andromeda', 'Andromeda'), ('Air Pump', 'Air Pump'), ('Bird of Paradise', 'Bird of Paradise'), ('Water Bearer', 'Water Bearer'), ('Eagle', 'Eagle'), ('Altar', 'Altar'), ('Ram', 'Ram'), ('Charioteer', 'Charioteer'), ('Herdsman', 'Herdsman'), ('Chisel', 'Chisel'), ('Giraffe', 'Giraffe'), ('Crab', 'Crab'), ('Hunting Dogs', 'Hunting Dogs'), ('Greater Dog', 'Greater Dog'), ('Lesser Dog', 'Lesser Dog'), ('Sea Goat', 'Sea Goat'), ('Keel', 'Keel'), ('Cassiopeia', 'Cassiopeia'), ('Centaur', 'Centaur'), ('Cepheus', 'Cepheus'), ('Whale (or Sea Monster)', 'Whale (or Sea Monster)'), ('Chameleon', 'Chameleon'), ('Compass (drafting tool)', 'Compass (drafting tool)'), ('Dove', 'Dove'), ('Berenice’s Hair', 'Berenice’s Hair'), ('Southern Crown', 'Southern Crown'), ('Northern Crown', 'Northern Crown'), ('Crow', 'Crow'), ('Cup', 'Cup'), ('Southern Cross', 'Southern Cross'), ('Swan', 'Swan'), ('Dolphin', 'Dolphin'), ('Dolphinfish', 'Dolphinfish'), ('Dragon', 'Dragon'), ('Little Horse (Foal)', 'Little Horse (Foal)'), ('Eridanus (river)', 'Eridanus (river)'), ('Furnace', 'Furnace'), ('Twins', 'Twins'), ('Crane', 'Crane'), ('Hercules', 'Hercules'), ('Pendulum Clock', 'Pendulum Clock'), ('Hydra', 'Hydra'), ('Water Snake', 'Water Snake'), ('Indian', 'Indian'), ('Lizard', 'Lizard'), ('Lion', 'Lion'), ('Lesser Lion', 'Lesser Lion'), ('Hare', 'Hare'), ('Scales', 'Scales'), ('Wolf', 'Wolf'), ('Lynx', 'Lynx'), ('Lyre', 'Lyre'), ('Table Mountain (Mons Mensae)', 'Table Mountain (Mons Mensae)'), ('Microscope', 'Microscope'), ('Unicorn', 'Unicorn'), ('Fly', 'Fly'), ('Level', 'Level'), ('Octant', 'Octant'), ('Serpent Bearer', 'Serpent Bearer'), ('Orion (the Hunter)', 'Orion (the Hunter)'), ('Peacock', 'Peacock'), ('Pegasus', 'Pegasus'), ('Perseus', 'Perseus'), ('Phoenix', 'Phoenix'), ('Easel', 'Easel'), ('Fishes', 'Fishes'), ('Southern Fish', 'Southern Fish'), ('Stern', 'Stern'), ('Compass (mariner’s compass)', 'Compass (mariner’s compass)'), ('Reticle', 'Reticle'), ('Arrow', 'Arrow'), ('Archer', 'Archer'), ('Scorpion', 'Scorpion'), ('Sculptor', 'Sculptor'), ('Shield (of Sobieski)', 'Shield (of Sobieski)'), ('Snake', 'Snake'), ('Sextant', 'Sextant'), ('Bull', 'Bull'), ('Telescope', 'Telescope'), ('Triangle', 'Triangle'), ('Southern Triangle', 'Southern Triangle'), ('Toucan', 'Toucan'), ('Great Bear', 'Great Bear'), ('Little Bear', 'Little Bear'), ('Sails', 'Sails'), ('Virgin (Maiden)', 'Virgin (Maiden)'), ('Flying Fish', 'Flying Fish'), ('Fox', 'Fox')], default='Andromeda', max_length=255),
        ),
        migrations.AlterField(
            model_name='scienceplan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 14, 19, 12, 136267, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scienceplan',
            name='submitter',
            field=models.CharField(default="Submitter's name'", max_length=50),
        ),
        migrations.AlterField(
            model_name='scienceplan',
            name='telescope_location',
            field=models.CharField(choices=[('HAWAII', 'HAWAII'), ('CHILE', 'CHILE')], default='HAWAII', max_length=255),
        ),
    ]
