# Generated by Django 3.2 on 2021-05-09 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_app', '0005_auto_20210509_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scienceplan',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 14, 20, 23, 998483, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scienceplan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 14, 20, 23, 998483, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scienceplan',
            name='submitter',
            field=models.CharField(default="Submitter's name", max_length=50),
        ),
    ]
