# Generated by Django 3.2 on 2021-05-09 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_app', '0006_auto_20210509_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scienceplan',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 6, 20, 433780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scienceplan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 6, 20, 433780, tzinfo=utc)),
        ),
    ]
