# Generated by Django 3.2 on 2021-05-10 10:31

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_app', '0009_auto_20210510_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scienceplan',
            name='id',
        ),
        migrations.AlterField(
            model_name='scienceplan',
            name='end_date',
            field=models.DateTimeField(default='10/05/2021 10:31:47', validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 5, 10, 10, 31, 47, 455779, tzinfo=utc), message='The end date is invalid.')]),
        ),
        migrations.AlterField(
            model_name='scienceplan',
            name='plan_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scienceplan',
            name='start_date',
            field=models.DateTimeField(default='10/05/2021 10:31:47', validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 5, 10, 10, 31, 47, 455779, tzinfo=utc), message='The start date is invalid.')]),
        ),
    ]
